eureka:
  instance:
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8768/eureka/
  instance:
    hostname: localhost 
    
    spring:
      cloud:
        discovery:
        enabled: true
      Zipkin:
        enabled: true
        
